import { EventEmitter } from '@angular/core';
import { ToastrService } from 'ngx-toastr';
import { AiddxService } from '../../services/aiddx.service';
import { MatDialog } from '@angular/material/dialog';
import * as i0 from "@angular/core";
export declare class AillmddxComponent {
    private ddxSvc;
    private dialog;
    private toastr;
    private env?;
    patientInfo: any;
    visit: any;
    existingDiagnosis: any[];
    diagnosisSelected: EventEmitter<string[]>;
    furtherQuestionsListReceived: EventEmitter<any[]>;
    diagnosisReceived: EventEmitter<any[]>;
    notes: string;
    visitCompleted: boolean;
    isLoading: boolean;
    hasError: boolean;
    noData: boolean;
    insufficientData: boolean;
    isActive: boolean;
    conclusion: string;
    treatment: string;
    menuContent: string;
    diagnosisName: any;
    questions: {
        title: string;
        items: string[];
    }[];
    diagnosisList: any;
    furtherQuestionsList: any;
    selectedDiagnosis: string[];
    apiResponseChanged: boolean;
    constructor(ddxSvc: AiddxService, dialog: MatDialog, toastr: ToastrService, env?: any);
    ngOnInit(): void;
    getAIDiagnosis(notes?: string): void;
    getAIDiagnosisWithRetry(notes?: string): void;
    onTryAgain(): void;
    onAIDiagnosisChange(event: any): void;
    isDiagnosisExists(diagnosis: string): boolean;
    isDiagnosisSelected(diagnosis: string): boolean;
    setMenuContent(title: any, likelihood: any, item: any): void;
    private isValidDdxResponse;
    isObject(value: any): boolean;
    static ɵfac: i0.ɵɵFactoryDeclaration<AillmddxComponent, [null, null, null, { optional: true; }]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AillmddxComponent, "app-aillmddx", never, { "patientInfo": "patientInfo"; "visit": "visit"; "existingDiagnosis": "existingDiagnosis"; "notes": "notes"; "visitCompleted": "visitCompleted"; }, { "diagnosisSelected": "diagnosisSelected"; "furtherQuestionsListReceived": "furtherQuestionsListReceived"; "diagnosisReceived": "diagnosisReceived"; }, never, never, false>;
}
